import { Inter } from "next/font/google"
import "./globals.css"
import { Inter as FontSans } from "next/font/google"
import { Providers } from "@/context/Providers"
import { UiProvider } from "@/context/UiContext"
const inter = Inter({ subsets: ["latin"] })
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "JOBIT",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  dark:bg-dark-main transition text-textColor bg-main`}>
        <Providers>
          <UiProvider>{children}</UiProvider>{" "}
        </Providers>
      </body>
    </html>
  )
}
